"""templates and resume versions

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-08 00:16:47.439553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'name', name='uq_templates_kind_name')
    )
    op.create_table('resume_versions',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('job_posting_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('rendered_pdf_path', sa.Text(), nullable=False),
    sa.Column('rendered_tex_path', sa.Text(), nullable=False),
    sa.Column('ats_verification_passed', sa.Boolean(), nullable=False),
    sa.Column('ats_extracted_text_path', sa.Text(), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_versions')
    op.drop_table('templates')
    # ### end Alembic commands ###
